"""MuJoCo simulation of the tabletop hexapod prototype.

This is the prototype-scale counterpart to ``mujoco_walker.py``.  It keeps
the same public API used by the RL stack:

    build_world(...)
    TripodGait
    _set_stance_qpos(...)

so ``hexapod_env.py``, ``train_walker.py`` and ``rollout_walker.py`` can be
reused for the prototype with only module aliasing.
"""

from __future__ import annotations

import argparse
import math
import os
import sys
import time

import mujoco
import numpy as np

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, THIS_DIR)
import hexapod_prototype as HP  # noqa: E402
from part_palette import PART_COLORS  # noqa: E402


M = 0.001  # mm -> m

APOTHEM = HP.CHASSIS_FLAT_TO_FLAT / 2.0 * M
COXA = HP.COXA_LENGTH * M
FEMUR = HP.FEMUR_LENGTH * M
TIBIA = HP.TIBIA_LENGTH * M
STANCE_FEMUR = math.radians(HP.STANCE_FEMUR_DEG)
STANCE_TIBIA = math.radians(HP.STANCE_TIBIA_DEG)

# Output-shaft stack above the chassis-plate top (= bracket flange top
# face).  Design B (May 2026): collapsed from
#   (BODY_H - RIM_Z) + SERVO_OUTPUT_H + PLASTIC_HORN_H + HORN_ADAPTER_T
# down to
#   (BODY_H - RIM_Z) + SERVO_OUTPUT_H + HORN_STACK_H
# now that ``HORN_STACK_H == PLASTIC_HORN_H == 5 mm`` and the printed
# servo_horn_adapter has been retired (the link bolts directly to the
# 20 mm aluminum 25T disc horn).
YAW_OUTPUT_HEIGHT = (
    (HP.SERVO_BODY_H - HP.WELL_RIM_Z)
    + HP.SERVO_OUTPUT_H
    + HP.HORN_STACK_H
) * M
LEG_RADIAL = APOTHEM

# Electronics-tray chassis-frame placement (May 2026 expansion: tray
# centre moved from (+35, 0) to (0, 0) so the tray's 4 chassis-mount
# holes line up with the chassis-side 35-mm-radius pattern).  Mirrors
# ``HP.ELEC_TRAY_CENTRE_X / Y`` in metres.
HP_ELEC_TRAY_CX_M = HP.ELEC_TRAY_CENTRE_X * M
HP_ELEC_TRAY_CY_M = HP.ELEC_TRAY_CENTRE_Y * M

CHASSIS_MASS = 0.55
# Jun 2026 bearing-sandwich refit: each link's mass = its printed PLA
# fittings + the CF tube + the STS3215 (~0.060 kg) that is *mounted on it*.
# The hip servo rides the coxa fixed side; the knee servo rides the femur
# knee bracket; the tibia carries no servo (driven from the femur), so it
# is the lightest segment.  CF tubes (~0.008-0.010 kg) replace the old
# solid PLA spars.
COXA_MASS = 0.110    # PLA coxa (pad+arm+hip bracket+bearing housing) + hip STS3215
FEMUR_MASS = 0.105   # hip yoke + knee bracket + Ø8 CF tube + knee STS3215
TIBIA_MASS = 0.040   # knee yoke + Ø8 CF tube + TPU foot boot (no servo;
                     # Aug 2026: hinged fitting+pad retired, ~15 g lighter)

# DS3225-class hobby servos are around 25 kg-cm ~= 2.45 N*m.  Keep a little
# below that so the sim does not assume impossible torque.
TORQUE_LIMIT = 2.2
KP_YAW = 18.0
KP_PITCH = 26.0
KP_KNEE = 24.0
DAMP_YAW = 0.35
DAMP_PITCH = 0.45
DAMP_KNEE = 0.40
ARMATURE = 0.0004

# Aug 2026 TPU boot: ground contact is a sphere of the boot's outer radius
# on the tibia centerline whose surface reaches exactly tibia-local
# x = TIBIA (the kinematic tip).  Aug 19 2026: no longer an approximation
# -- the printed boot's tip IS this hemisphere (the old flat chamfer-rimmed
# face rode its rim edge at off-perpendicular tibia angles, causing the
# real-floor stuck/slip failures the sim never saw).
FOOT_R = HP.FOOT_BOOT_OD / 2.0 * M
BOOT_TIP_CTR = HP.TIBIA_LENGTH * M - FOOT_R   # sphere centre along tibia +X


# ---------------------------------------------------------------------------
# Optional visual meshes -- generated by hexapod_prototype.main() into
# ``stl_prototype/`` (the same STL bundle that the slicer-ready prototype
# uses).  When all expected files are present the MJCF references them as
# scaled mesh visuals so the rendered scene shows the ACTUAL printed parts
# (chassis plates, brackets, every link, foot pads) plus the real
# hobby-servo silhouettes in every well/cradle -- not the box / capsule
# placeholders that earlier MJCF versions drew.  When missing we fall
# back to the primitive geometry used historically (useful in CI before
# anyone has run ``hexapod_prototype.py``).
#
# Important: these are RENDERED-AS-VISUAL only.  They keep
# ``contype="0" conaffinity="0"`` (via ``class="visual"``), so they do
# NOT participate in MuJoCo's contact solver.  Self-collision between
# printed parts is a DESIGN-RULE check, and we run that on the actual
# boolean meshes via ``_verify_prototype.check_workspace_self_collision``
# -- MuJoCo's convex-hull collision would only report false positives on
# parts like the C-shaped coxa_bracket.

_SERVO_BODY_STL = HP.stl_path("servo_body")
_SERVO_HORN_STL = HP.stl_path("servo_horn")
USE_SERVO_MESHES = (os.path.isfile(_SERVO_BODY_STL)
                     and os.path.isfile(_SERVO_HORN_STL))

# Printed-part STLs, in the same scaled-mm-to-m convention as the servo
# meshes.  All are emitted by ``hexapod_prototype.main`` and are
# what the assembly preview + STL bundles consume.
# Aug 2026: uno_q_tray / buck_tray / spider_carapace RETIRED from print.
_PART_STL_NAMES = (
    "chassis_top",
    "chassis_bottom",
    "coxa_link",
    "femur_link",
    "tibia_link",
    "foot_boot",
    "servo_clamp_cap",
)
USE_PART_MESHES = all(
    os.path.isfile(HP.stl_path(name))
    for name in _PART_STL_NAMES
)

# Yaw servo (mounted to chassis, output up).  In leg-local coords with +X
# pointing radially outward, the yaw servo's body-bottom-centre sits at
# (-SERVO_OUTPUT_X, 0, -WELL_RIM_Z), with mesh-local +X aligned to leg +X.
YAW_BODY_DX = -HP.SERVO_OUTPUT_X * M     # offset along leg radial axis
YAW_BODY_DZ = -HP.WELL_RIM_Z * M         # below chassis plate top
YAW_HORN_DZ = ((HP.SERVO_BODY_H - HP.WELL_RIM_Z) + HP.SERVO_OUTPUT_H) * M

# Hip-pitch + knee-pitch servos sit in their cradles with output along the
# joint's pitch axis (+Y in leg-local).  Mesh local +Z must map to leg +Y,
# which is a -90 deg rotation about the leg-local X axis.  Body-bottom-centre
# offset (relative to joint axis): (-SERVO_OUTPUT_X, -(SERVO_BODY_H +
# SERVO_OUTPUT_H), hip_drop) -- after the rotation, that lands the spline
# tip on the joint axis at the chosen drop.
PITCH_ARM_T = HP.COXA_ARM_T     # MUST match make_coxa_link()'s arm_t
# Single source of truth: ``hexapod_prototype.COXA_HIP_DROP`` already
# includes the ``WELL_Z_DROP_EXTRA = 4 mm`` extra well drop that landed
# in the spar-clearance / horn-stack-clearance fix.  Re-deriving the
# formula here lost the +4 mm offset and made the rendered hip-servo
# body float 4 mm above the real well.
HIP_DROP = HP.COXA_HIP_DROP * M
HIP_BODY_DX = -HP.SERVO_OUTPUT_X * M
HIP_BODY_DY = -(HP.SERVO_BODY_H + HP.SERVO_OUTPUT_H) * M
HIP_BODY_DZ = HIP_DROP
# Jun 2026 re-centre: the hip bracket is centred on the yaw axis, so the
# hip-pitch joint axis sits at coxa-link y = COXA_HIP_ANCHOR_Y (tangential)
# instead of y=0.  The femur sub-tree + hip servo/horn/cap visuals all
# shift by this amount in the coxa frame.
HIP_ANCHOR_Y = HP.COXA_HIP_ANCHOR_Y * M

# Quaternion (w, x, y, z) for -90 deg about X axis: cos(-pi/4) = sqrt(2)/2,
# sin(-pi/4) = -sqrt(2)/2.
_PITCH_QUAT = (math.cos(-math.pi / 4.0), math.sin(-math.pi / 4.0), 0.0, 0.0)


def _palette_materials_xml() -> str:
    """Emit one ``<material>`` per entry in PART_COLORS.

    Each printable / proxy part type maps to ``palette_<part_type>`` so
    every visual ``<geom>`` can pick its color by name and stay in
    lockstep with the PyVista build inspector.  Aliases like
    ``chassis_plate_a`` are emitted too (same RGBA as their canonical
    sibling) so future XML can reference either spelling.
    """
    lines = []
    for part_type, (r, g, b) in PART_COLORS.items():
        lines.append(
            f'<material name="palette_{part_type}" '
            f'rgba="{r:.4f} {g:.4f} {b:.4f} 1" '
            f'specular="0.25" shininess="0.25"/>'
        )
    return "\n    ".join(lines)


def _servo_body_geom_xml(local_class: str, body_offset: tuple[float, float, float],
                          quat: tuple[float, float, float, float] | None = None,
                          name: str | None = None,
                          material: str = "palette_servo_body") -> str:
    """Single visual mesh geom for one servo body in some parent body frame."""
    name_attr = f' name="{name}"' if name else ""
    if quat is None:
        quat_attr = ""
    else:
        qw, qx, qy, qz = quat
        quat_attr = f' quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}"'
    bx, by, bz = body_offset
    return (
        f'<geom class="{local_class}"{name_attr} type="mesh" mesh="servo_body" '
        f'pos="{bx:.5f} {by:.5f} {bz:.5f}"{quat_attr} material="{material}"/>'
    )


def _servo_horn_geom_xml(local_class: str, body_offset: tuple[float, float, float],
                          quat: tuple[float, float, float, float] | None = None,
                          name: str | None = None,
                          material: str = "palette_servo_horn") -> str:
    name_attr = f' name="{name}"' if name else ""
    if quat is None:
        quat_attr = ""
    else:
        qw, qx, qy, qz = quat
        quat_attr = f' quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}"'
    bx, by, bz = body_offset
    return (
        f'<geom class="{local_class}"{name_attr} type="mesh" mesh="servo_horn" '
        f'pos="{bx:.5f} {by:.5f} {bz:.5f}"{quat_attr} material="{material}"/>'
    )


def _servo_clamp_cap_geom_xml(local_class: str,
                               body_offset: tuple[float, float, float],
                               quat: tuple[float, float, float, float] | None = None,
                               name: str | None = None,
                               material: str = "palette_servo_clamp_cap") -> str:
    """Single visual mesh geom for one sandwich-joint clamp cap.  The cap
    is modelled in the servo well-local frame (same origin/axes as the
    servo body), so it stamps at the same offset/quat as the body."""
    name_attr = f' name="{name}"' if name else ""
    if quat is None:
        quat_attr = ""
    else:
        qw, qx, qy, qz = quat
        quat_attr = f' quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}"'
    bx, by, bz = body_offset
    return (
        f'<geom class="{local_class}"{name_attr} type="mesh" '
        f'mesh="servo_clamp_cap" '
        f'pos="{bx:.5f} {by:.5f} {bz:.5f}"{quat_attr} material="{material}"/>'
    )


HFIELD_NROW = 128
HFIELD_NCOL = 128
HFIELD_SIZE = 2.5
HFIELD_MAX_Z = 0.018
HFIELD_BASE = 0.08
HFIELD_SPAWN_FLAT_R = 0.32


def make_terrain_heightmap(seed: int = 0) -> np.ndarray:
    """Small indoor-scale terrain normalized to [0, 1]."""
    rng = np.random.default_rng(seed)
    xs = np.linspace(-HFIELD_SIZE, HFIELD_SIZE, HFIELD_NCOL)
    ys = np.linspace(-HFIELD_SIZE, HFIELD_SIZE, HFIELD_NROW)
    X, Y = np.meshgrid(xs, ys, indexing="xy")

    h = (
        0.40 * np.sin(4.0 * X + 0.7)
        + 0.30 * np.cos(3.1 * Y - 0.2)
        + 0.20 * np.sin(8.0 * X + 5.0 * Y)
    )
    for _ in range(5):
        cx, cy = rng.uniform(-1.8, 1.8, size=2)
        sigma = rng.uniform(0.10, 0.28)
        amp = rng.uniform(0.15, 0.45)
        h += amp * np.exp(-((X - cx) ** 2 + (Y - cy) ** 2) / (2 * sigma ** 2))

    h -= h.min()
    if h.max() > 0:
        h /= h.max()

    R = np.hypot(X, Y)
    fade = np.clip((R - HFIELD_SPAWN_FLAT_R) / (HFIELD_SPAWN_FLAT_R * 0.8), 0, 1)
    h *= fade ** 1.2
    if h.max() > 0:
        h /= h.max()
    return h.astype(np.float32)


def sample_terrain_height(heights: np.ndarray, x: float, y: float) -> float:
    nrow, ncol = heights.shape
    fx = (x + HFIELD_SIZE) / (2 * HFIELD_SIZE) * (ncol - 1)
    fy = (y + HFIELD_SIZE) / (2 * HFIELD_SIZE) * (nrow - 1)
    fx = max(0.0, min(ncol - 1.0001, fx))
    fy = max(0.0, min(nrow - 1.0001, fy))
    c0 = int(fx)
    r0 = int(fy)
    dx = fx - c0
    dy = fy - r0
    h00 = heights[r0, c0]
    h01 = heights[r0, c0 + 1]
    h10 = heights[r0 + 1, c0]
    h11 = heights[r0 + 1, c0 + 1]
    h = h00 * (1 - dx) * (1 - dy) + h01 * dx * (1 - dy) + h10 * (1 - dx) * dy + h11 * dx * dy
    return float(h) * HFIELD_MAX_Z


def make_obstacles_xml(
    heights: np.ndarray,
    *,
    count: int = 8,
    seed: int = 0,
    inner_radius: float | None = None,
    outer_radius: float | None = None,
) -> str:
    if count <= 0:
        return ""
    rng = np.random.default_rng(seed * 31 + 17)
    if inner_radius is None:
        inner_radius = HFIELD_SPAWN_FLAT_R + 0.18
    if outer_radius is None:
        outer_radius = HFIELD_SIZE * 0.75

    placed: list[tuple[float, float, float]] = []
    snippets = []

    def nonoverlap(x, y, r):
        if math.hypot(x, y) - r < inner_radius:
            return False
        return all(math.hypot(px - x, py - y) > r + pr + 0.08 for px, py, pr in placed)

    for idx in range(count):
        sx = float(rng.uniform(0.035, 0.10))
        sy = float(rng.uniform(0.025, 0.08))
        sz = float(rng.uniform(0.010, 0.035))
        yaw = float(rng.uniform(0, 2 * math.pi))
        r_excl = math.hypot(sx, sy) + 0.04
        xy = None
        for _ in range(60):
            rr = rng.uniform(inner_radius, outer_radius)
            th = rng.uniform(0, 2 * math.pi)
            x, y = rr * math.cos(th), rr * math.sin(th)
            if nonoverlap(x, y, r_excl):
                xy = (x, y)
                break
        if xy is None:
            continue
        x, y = xy
        z = sample_terrain_height(heights, x, y) + sz
        qw, qz = math.cos(yaw / 2), math.sin(yaw / 2)
        snippets.append(
            f'<geom name="obs_{idx}" type="box" size="{sx:.4f} {sy:.4f} {sz:.4f}" '
            f'pos="{x:.4f} {y:.4f} {z:.4f}" quat="{qw:.5f} 0 0 {qz:.5f}" '
            f'rgba="0.52 0.45 0.35 1" friction="1.5 0.05 0.0001"/>'
        )
        placed.append((x, y, r_excl))
    return "\n      ".join(snippets)


# Aug 2026 TPU boot: the contact sphere sits ON the tibia centerline at
# BOOT_TIP_CTR from the knee (surface tangent at the TIBIA_LENGTH tip).
# The old hinged pad's PAD_HINGE_Z below-centerline drop is retired.


def stance_foot_z_relative_to_hip() -> float:
    """Contact-sphere-centre z relative to the hip at the stance pose."""
    p = STANCE_FEMUR
    pt = STANCE_FEMUR + STANCE_TIBIA
    knee_z = -FEMUR * math.sin(p)
    return knee_z - BOOT_TIP_CTR * math.sin(pt)


def stance_chassis_height() -> float:
    return -YAW_OUTPUT_HEIGHT - stance_foot_z_relative_to_hip() + FOOT_R + 0.008


def foot_horizontal_reach() -> float:
    p = STANCE_FEMUR
    pt = STANCE_FEMUR + STANCE_TIBIA
    return COXA + FEMUR * math.cos(p) + TIBIA * math.cos(pt)


D_FOOT = foot_horizontal_reach()


def build_xml(obstacles_xml: str = "") -> str:
    base_z = stance_chassis_height()
    leg_blocks = []
    actuator_blocks = []
    sensor_blocks = []
    yaw_chassis_blocks = []
    yaw_col_blocks = []
    for i in range(6):
        a = (i + 0.5) * math.pi / 3.0
        x = LEG_RADIAL * math.cos(a)
        y = LEG_RADIAL * math.sin(a)
        qw = math.cos(a / 2.0)
        qz = math.sin(a / 2.0)
        leg_blocks.append(_leg_xml(i, x, y, YAW_OUTPUT_HEIGHT, qw, qz))
        actuator_blocks.append(_leg_actuators(i))
        sensor_blocks.append(_leg_sensors(i))
        yaw_chassis_blocks.append(_yaw_servo_chassis_xml(i, a, x, y, qw, qz))
        yaw_col_blocks.append(_yaw_servo_collision_xml(i, a, qw, qz))

    yaw_chassis_xml = "\n      ".join(yaw_chassis_blocks) if USE_SERVO_MESHES else ""
    yaw_col_xml = "\n      ".join(yaw_col_blocks)
    chassis_visuals_xml = _chassis_visuals_xml()

    mesh_asset_xml = ""
    compiler_attrs = 'angle="radian" coordinate="local" autolimits="true"'
    if USE_SERVO_MESHES or USE_PART_MESHES:
        # Absolute paths: printables live in stl_prototype/, reference
        # visuals (servos, tibia_link, …) in stl_reference/.
        mesh_lines: list[str] = []
        if USE_SERVO_MESHES:
            mesh_lines.append(
                f'<mesh name="servo_body" file="{_SERVO_BODY_STL}" '
                f'scale="0.001 0.001 0.001"/>'
            )
            mesh_lines.append(
                f'<mesh name="servo_horn" file="{_SERVO_HORN_STL}" '
                f'scale="0.001 0.001 0.001"/>'
            )
        if USE_PART_MESHES:
            # tibia_link.stl is drawn from the old mesh landmark rather than
            # the kinematic knee axis.  As of the Aug 21 measured-geometry
            # update, physics / IK use the measured 150 mm knee->boot-tip
            # span, while the legacy STL visual still lands its boot tip at
            # about x=157.5 mm.  Squash only the visual so rendered parts
            # line up with the contact sphere; do not move physics.
            #
            # Historical note: this used to be a much larger correction when
            # the stale kinematic tibia was 128 mm:
            #   tibia_link.stl is drawn ~29.5 mm LONGER than the kinematic
            # tibia: hexapod_prototype's sandwich make_tibia_link measures
            # the tube run from the yoke SOCKET (x ≈ +29.5) instead of the
            # knee axis, so the boot tip landed at x ≈ 157.5 while physics,
            # IK and firmware put the foot tip at x = 128. Rendered raw,
            # that extra visual length poked through the floor in
            # every stance ("legs through the ground", operator 08-09) even
            # though the contact sphere sat at the physics tip.
            tibia_fix = TIBIA / 0.1575   # kinematic tip / measured mesh tip
            for name in _PART_STL_NAMES:
                sx = 0.001 * tibia_fix if name == "tibia_link" else 0.001
                # Logical mesh name stays plain (geoms reference mesh="femur_link").
                mesh_lines.append(
                    f'<mesh name="{name}" file="{HP.stl_path(name)}" '
                    f'scale="{sx:.7f} 0.001 0.001"/>'
                )
        mesh_asset_xml = "\n    ".join(mesh_lines)

    return f"""<mujoco model="hexapod_prototype">
  <compiler {compiler_attrs}/>
  <option gravity="0 0 -9.81" timestep="0.002" iterations="50" solver="Newton" cone="elliptic"/>
  <visual>
    <global offwidth="1920" offheight="1200"/>
  </visual>

  <default>
    <joint armature="{ARMATURE}" damping="0.01" limited="true"/>
    <geom solref="0.006 1" solimp="0.95 0.99 0.001"/>
    <default class="visual">
      <geom contype="0" conaffinity="0" group="2" density="0"/>
    </default>
    <default class="collision">
      <geom group="3" rgba="1 0 0 0.18" condim="4" friction="1.3 0.04 0.0001"/>
    </default>
    <default class="foot">
      <geom group="3" rgba="0.02 0.02 0.02 1" condim="6" friction="2.0 0.1 0.001"
            solref="0.01 1" solimp="0.95 0.99 0.001"/>
    </default>
    <default class="legcol">
      <!-- Leg-segment ground collision (Aug 2026). Before this class,
           only the foot spheres / chassis box / yaw servo boxes collided:
           femur, knee servo and tibia were visual-only, so rise/lower
           policies learned to sweep shins THROUGH the floor (operator
           spotted it in MuJoCo; on hardware that motion jams the leg and
           strips a servo). Bitmask contype=4 / conaffinity=0 pairs these
           ONLY with the floor plane (conaffinity=5): no leg-leg or
           leg-chassis contacts, so the convex-hull false-positive problem
           that made leg links visual-only in the first place (see the
           mesh comment above) stays avoided. -->
      <geom contype="4" conaffinity="0" group="3" rgba="1 0.55 0 0.25"
            condim="3" friction="1.0 0.02 0.0001"/>
    </default>
  </default>

  <asset>
    <texture name="skybox" type="skybox" builtin="gradient" rgb1="0.7 0.85 1.0" rgb2="0.4 0.5 0.7" width="256" height="256"/>
    <texture name="grid" type="2d" builtin="checker" rgb1="0.25 0.3 0.35" rgb2="0.18 0.22 0.27" width="300" height="300"/>
    <material name="grid" texture="grid" texrepeat="6 6" reflectance="0.15"/>
    <material name="frame" rgba="0.78 0.82 0.85 1" specular="0.25" shininess="0.25"/>
    <material name="motor" rgba="0.05 0.05 0.06 1" specular="0.2" shininess="0.2"/>
    <material name="battery" rgba="0.16 0.16 0.24 1"/>
    <material name="rubber" rgba="0.02 0.02 0.02 1"/>
    {_palette_materials_xml()}
    <texture name="terrain_tex" type="2d" builtin="checker" rgb1="0.34 0.45 0.30" rgb2="0.26 0.36 0.22" width="320" height="320"/>
    <material name="terrain_mat" texture="terrain_tex" texrepeat="12 12" reflectance="0.05" shininess="0.0"/>
    <hfield name="terrain" nrow="{HFIELD_NROW}" ncol="{HFIELD_NCOL}" size="{HFIELD_SIZE} {HFIELD_SIZE} {HFIELD_MAX_Z} {HFIELD_BASE}"/>
    {mesh_asset_xml}
  </asset>

  <worldbody>
    <light name="sun" pos="2 -1.5 2.2" dir="-0.6 0.4 -1" castshadow="true"/>
    <geom name="floor" type="plane" size="8 8 0.05" pos="0 0 -0.001" material="grid" friction="1.5 0.05 0.0001" conaffinity="5"/>
    <geom name="terrain" type="hfield" hfield="terrain" material="terrain_mat" friction="1.5 0.05 0.0001" condim="4"/>
      {obstacles_xml}

    <body name="chassis" pos="0 0 {base_z:.5f}">
      <freejoint name="root"/>
      <site name="chassis_imu" pos="0 0 0.035" size="0.008"/>
      <inertial pos="0 0 0.018" mass="{CHASSIS_MASS}" diaginertia="0.006 0.006 0.010"/>
      {chassis_visuals_xml}
      <geom class="collision" name="chassis_box" type="box" pos="0 0 0.014" size="0.115 0.105 0.020"/>
      {yaw_col_xml}
      {yaw_chassis_xml}

{''.join(leg_blocks)}
    </body>
  </worldbody>

  <actuator>
{''.join(actuator_blocks)}
  </actuator>

  <sensor>
{''.join(sensor_blocks)}
    <accelerometer name="chassis_acc" site="chassis_imu"/>
    <gyro name="chassis_gyro" site="chassis_imu"/>
    <framepos name="chassis_pos" objtype="body" objname="chassis"/>
    <framezaxis name="chassis_up" objtype="body" objname="chassis"/>
  </sensor>
</mujoco>
"""


# Fallback-visual colors matched to the printed robot (red PETG, blue PETG
# brackets, black STS3215 bodies / carbon-fibre tube).
_RED = "0.72 0.11 0.10"
_BLUE = "0.15 0.33 0.72"
_BLACK = "0.10 0.10 0.11"


def _chassis_visuals_xml() -> str:
    """Visual geoms attached to the chassis body.  Chassis origin (z=0)
    = bottom-plate TOP face = bracket-chassis bolt plane = same plane
    the legs treat as 'edge midpoint at z=0'.

    When the printed-part STLs are available we render the real
    chassis_top + chassis_bottom plates, the battery holder, and the
    electronics tray.  Otherwise we fall back to the historical
    placeholder cylinder + boxes so the model still loads in CI before
    anyone has run ``hexapod_prototype.py``.
    """
    if not USE_PART_MESHES:
        # Photo-faithful placeholders: two red hex plates, red electronics
        # tower between/above them, dark display on the tower top.
        flat_to_flat = HP.CHASSIS_FLAT_TO_FLAT / 2.0 * M
        hex_r = flat_to_flat / math.cos(math.pi / 6)
        gap = HP.CHASSIS_GAP * M
        plate_t = HP.CHASSIS_PLATE_T * M
        return (
            '<geom class="visual" type="cylinder" '
            f'size="{hex_r:.5f} {plate_t / 2:.5f}" '
            f'pos="0 0 {-plate_t / 2:.5f}" '
            f'euler="0 0 {math.pi / 6:.5f}" rgba="{_RED} 1"/>\n'
            '      <geom class="visual" type="cylinder" '
            f'size="{hex_r * 0.92:.5f} {plate_t / 2:.5f}" '
            f'pos="0 0 {gap + plate_t / 2:.5f}" '
            f'euler="0 0 {math.pi / 6:.5f}" rgba="{_RED} 1"/>\n'
            '      <geom class="visual" type="box" size="0.032 0.032 0.030" '
            f'pos="0 0 {gap + plate_t + 0.030:.5f}" '
            f'euler="0 0 {math.pi / 6:.5f}" rgba="{_RED} 1"/>\n'
            '      <geom class="visual" type="box" size="0.017 0.013 0.0012" '
            f'pos="0 0 {gap + plate_t + 0.0615:.5f}" rgba="0.05 0.08 0.10 1"/>'
        )

    plate_t = HP.CHASSIS_PLATE_T * M
    gap = HP.CHASSIS_GAP * M
    # Jun 2026 deck redesign retired the clip-in battery_holder + in-gap
    # electronics_tray.  Aug 2026 as-built stack retires the printed
    # uno_q_tray / buck_tray / spider_carapace too — electronics live on
    # the magnet hex board (extra_stl), not MuJoCo mesh assets here.
    # chassis_top's top face sits at chassis-local z = gap + plate_t/2.
    # Aug 2026: TWO shorty packs under the belly (block yawed 30 deg),
    # replacing the single bay pack.  This frame's z = 0 is the bottom
    # plate's TOP face, so the belly is at -plate_t - 4 mm (floor band)
    # and the pack centres hang BATTERY_H/2 below that.
    lipo_h = HP.BATTERY_H * M
    lipo_cz = -(plate_t + 4.0 * M) - lipo_h / 2.0
    yaw = HP.BATTERY_UNDER_YAW_DEG
    off = (HP.BATTERY_D + HP.BATTERY_PACK_GAP) / 2.0
    a = np.deg2rad(yaw)
    lipo_geoms = ""
    for k, s in enumerate((-1.0, 1.0)):
        cx = (HP.BATTERY_UNDER_CENTRE[0] - s * off * np.sin(a)) * M
        cy = (HP.BATTERY_UNDER_CENTRE[1] + s * off * np.cos(a)) * M
        lipo_geoms += (
            f'\n      <geom class="visual" name="lipo_battery_{k}" '
            f'type="box" '
            f'size="{HP.BATTERY_W * M / 2.0:.5f} '
            f'{HP.BATTERY_D * M / 2.0:.5f} {lipo_h / 2.0:.5f}" '
            f'pos="{cx:.5f} {cy:.5f} {lipo_cz:.5f}" '
            f'euler="0 0 {yaw:.1f}" '
            'material="palette_chassis_top"/>'
        )
    return (
        f'<geom class="visual" name="chassis_bottom_mesh" type="mesh" '
        f'mesh="chassis_bottom" pos="0 0 {-plate_t:.5f}" '
        f'material="palette_chassis_bottom"/>\n'
        '      <geom class="visual" name="chassis_top_mesh" type="mesh" '
        f'mesh="chassis_top" pos="0 0 {gap:.5f}" '
        f'material="palette_chassis_top"/>'
        + lipo_geoms
    )


def _yaw_servo_collision_xml(i: int, a: float, qw: float, qz: float) -> str:
    """Collision box for the under-slung yaw servo + bracket.

    The six yaw servo assemblies hang below the bottom plate (chassis-frame
    z ≈ -38 mm → 0, measured from the reference servo mesh) and are what
    the real robot rests on when it sits down — without them the sim
    chassis sinks ~35 mm through the 'belly' until the plate box catches
    it. In the primitive render they also get a visual so the support is
    visible.
    """
    cx = (LEG_RADIAL + YAW_BODY_DX) * math.cos(a)
    cy = (LEG_RADIAL + YAW_BODY_DX) * math.sin(a)
    col = (f'<geom class="collision" name="L{i}_yaw_servo_col" type="box" '
           f'pos="{cx:.5f} {cy:.5f} -0.0192" '
           f'quat="{qw:.6f} 0 0 {qz:.6f}" size="0.026 0.013 0.019"/>')
    if USE_SERVO_MESHES:
        return col
    return (col + '\n      '
            f'<geom class="visual" type="box" '
            f'pos="{cx:.5f} {cy:.5f} -0.0192" '
            f'quat="{qw:.6f} 0 0 {qz:.6f}" size="0.027 0.014 0.020" '
            f'rgba="{_BLUE} 1"/>\n      '
            f'<geom class="visual" type="box" '
            f'pos="{cx:.5f} {cy:.5f} -0.0192" '
            f'quat="{qw:.6f} 0 0 {qz:.6f}" size="0.026 0.015 0.019" '
            f'rgba="{_BLACK} 1"/>')


def _yaw_servo_chassis_xml(i: int, a: float, x_leg: float, y_leg: float,
                            qw: float, qz: float) -> str:
    """Visual mesh geoms for the yaw servo body + horn in chassis-local coords.

    The yaw servo body hangs off the coxa bracket, fixed to the chassis -- it
    does NOT rotate with the coxa link.  Place it as a child of the chassis
    body so it stays put under all leg joints.
    """
    # Leg radial direction in chassis frame.
    cos_a = math.cos(a)
    sin_a = math.sin(a)
    # Body-bottom-centre in chassis-local (m).  Edge of chassis at LEG_RADIAL,
    # then YAW_BODY_DX along the radial axis (negative = inboard from edge).
    bx_x = (LEG_RADIAL + YAW_BODY_DX) * cos_a
    bx_y = (LEG_RADIAL + YAW_BODY_DX) * sin_a
    bx_z = YAW_BODY_DZ
    hx_x = LEG_RADIAL * cos_a
    hx_y = LEG_RADIAL * sin_a
    hx_z = YAW_HORN_DZ
    body = _servo_body_geom_xml(
        "visual", (bx_x, bx_y, bx_z),
        quat=(qw, 0.0, 0.0, qz),
        name=f"L{i}_yaw_servo",
    )
    horn = _servo_horn_geom_xml(
        "visual", (hx_x, hx_y, hx_z),
        quat=(qw, 0.0, 0.0, qz),
        name=f"L{i}_yaw_horn",
    )
    return body + "\n      " + horn


def _hip_servo_visual_xml(i: int) -> str:
    """Mesh hip-pitch servo body + horn in L{i}_yaw (coxa-link) local frame."""
    if not USE_SERVO_MESHES:
        # Black servo body in a blue bracket shell (as printed).
        return ('        <geom class="visual" type="box" '
                f'pos="0 -0.026 -0.017" size="0.021 0.011 0.020" rgba="{_BLUE} 1"/>\n'
                '        <geom class="visual" type="box" '
                f'pos="0 -0.026 -0.017" size="0.020 0.012 0.019" rgba="{_BLACK} 1"/>')
    body_offset = (COXA + HIP_BODY_DX, HIP_BODY_DY + HIP_ANCHOR_Y, HIP_BODY_DZ)
    horn_offset = (COXA, HIP_ANCHOR_Y, HIP_DROP)
    body = _servo_body_geom_xml(
        "visual", body_offset, quat=_PITCH_QUAT, name=f"L{i}_hip_servo",
    )
    horn = _servo_horn_geom_xml(
        "visual", horn_offset, quat=_PITCH_QUAT, name=f"L{i}_hip_horn",
    )
    # Sandwich-joint clamp cap shares the servo body's well-local frame.
    cap = _servo_clamp_cap_geom_xml(
        "visual", body_offset, quat=_PITCH_QUAT, name=f"L{i}_hip_clamp_cap",
    ) if USE_PART_MESHES else ""
    out = "        " + body + "\n        " + horn
    if cap:
        out += "\n        " + cap
    return out


def _knee_servo_visual_xml(i: int) -> str:
    """Mesh knee servo body + horn in L{i}_femur local frame."""
    if not USE_SERVO_MESHES:
        return ('          <geom class="visual" type="box" '
                f'pos="{FEMUR - 0.010:.5f} -0.026 0" size="0.021 0.011 0.020" '
                f'rgba="{_BLUE} 1"/>\n'
                '          <geom class="visual" type="box" '
                f'pos="{FEMUR - 0.010:.5f} -0.026 0" size="0.020 0.012 0.019" '
                f'rgba="{_BLACK} 1"/>')
    body_offset = (FEMUR + HIP_BODY_DX, HIP_BODY_DY, 0.0)
    horn_offset = (FEMUR, 0.0, 0.0)
    body = _servo_body_geom_xml(
        "visual", body_offset, quat=_PITCH_QUAT, name=f"L{i}_knee_servo",
    )
    horn = _servo_horn_geom_xml(
        "visual", horn_offset, quat=_PITCH_QUAT, name=f"L{i}_knee_horn",
    )
    cap = _servo_clamp_cap_geom_xml(
        "visual", body_offset, quat=_PITCH_QUAT, name=f"L{i}_knee_clamp_cap",
    ) if USE_PART_MESHES else ""
    out = "          " + body + "\n          " + horn
    if cap:
        out += "\n          " + cap
    return out


def _coxa_link_visual_xml(i: int) -> str:
    """Coxa-link visual in the L{i}_yaw body's local frame.

    The printed coxa_link.stl is built with its origin at the YAW
    horn-adapter TOP face (= the L{i}_yaw body's origin in the MJCF) and
    +X pointing outboard along the leg.  So no extra offset / rotation
    is needed; just stamp the mesh at the body origin.

    When the STL isn't available, fall back to the old placeholder box
    so the model still loads on a fresh checkout.
    """
    if USE_PART_MESHES:
        return (f'        <geom class="visual" name="L{i}_coxa_link_mesh" '
                f'type="mesh" mesh="coxa_link" material="palette_coxa_link"/>')
    return (f'        <geom class="visual" type="box" '
            f'pos="{COXA / 2:.5f} 0 0" '
            f'size="{COXA / 2:.5f} 0.010 0.004" rgba="{_RED} 1"/>')


def _femur_link_visual_xml(i: int) -> str:
    """Femur-link visual in the L{i}_femur body's local frame.

    The L{i}_femur body's origin lives on the hip-pitch joint axis at
    coxa-link (COXA, 0, 0).  In reality that axis is at coxa-link
    (COXA, 0, COXA_HIP_DROP) -- about 3.5 mm BELOW -- but the
    simulation has always treated the joint as living at z=0 in the
    parent.

    May 2026 collinear-pad refactor: the femur_link.stl's NEW local
    origin is the hip pad MATING FACE (= HORN_STACK_H above the joint
    axis along link +Y), not the joint axis itself.  Shift the mesh
    by (0, +HORN_STACK_H, 0) so its NEW local origin lands on the
    disc-horn-top plane = body +Y at HORN_STACK_H; pre-refactor the
    mesh sat at body origin (no shift).
    """
    if USE_PART_MESHES:
        pad_y = HP.HORN_STACK_H * M
        return (f'          <geom class="visual" name="L{i}_femur_link_mesh" '
                f'type="mesh" mesh="femur_link" '
                f'pos="0 {pad_y:.5f} 0" '
                f'material="palette_femur_link"/>')
    # Printed femur spar: thin red plate (LINK_THICKNESS x TIBIA_SPAR_H
    # cross-section), not a fat capsule.
    return (f'          <geom class="visual" type="box" '
            f'pos="{FEMUR / 2:.5f} 0 0" '
            f'size="{FEMUR / 2:.5f} 0.003 0.009" rgba="{_RED} 1"/>')


def _tibia_link_visual_xml(i: int) -> str:
    """Tibia-link visuals in the L{i}_tibia body's local frame.

    May 2026 collinear-pad refactor: tibia_link.stl's local origin is the
    knee pad MATING FACE = HORN_STACK_H above the knee joint axis along
    link +Y (= L{i}_tibia body +Y at HORN_STACK_H), not the joint axis
    itself.  Mesh is shifted (0, +HORN_STACK_H, 0) to land its origin on
    the disc-horn-top plane.  Aug 2026: the tibia_link mesh already
    includes the pressed-on TPU foot boot (make_tibia_link unions it), so
    no separate foot mesh is placed here.
    """
    if USE_PART_MESHES:
        pad_y = HP.HORN_STACK_H * M
        return (
            f'            <geom class="visual" name="L{i}_tibia_link_mesh" '
            f'type="mesh" mesh="tibia_link" '
            f'pos="0 {pad_y:.5f} 0" '
            f'material="palette_tibia_link"/>'
        )
    # As built: red knee yoke -> Ø8 carbon-fibre tube -> black TPU boot.
    boot_l = (HP.FOOT_BOOT_SOCKET_DEPTH + HP.FOOT_BOOT_TIP_L) * M
    return (
        f'            <geom class="visual" type="box" '
        f'pos="0.016 0 0" size="0.018 0.006 0.011" rgba="{_RED} 1"/>\n'
        f'            <geom class="visual" type="cylinder" '
        f'fromto="0.030 0 0 {TIBIA - boot_l:.5f} 0 0" size="0.004" '
        f'rgba="{_BLACK} 1"/>\n'
        f'            <geom class="visual" type="cylinder" '
        f'fromto="{TIBIA - boot_l:.5f} 0 0 {TIBIA:.5f} 0 0" '
        f'size="{FOOT_R:.5f}" rgba="{_BLACK} 1"/>'
    )


def _foot_boot_body_xml(i: int) -> str:
    """Fixed TPU-boot ground contact (Aug 2026 -- replaces the passive
    hinged foot pad body).  The body KEEPS the legacy name ``L{i}_pad``
    (and geom ``L{i}_foot`` / site ``L{i}_foot_site``) because the RL sim
    stack (sim_env / walk_task / domain_rand / eval) looks all three up
    by name for contact sensing and randomization.  No joint any more:
    the boot is pressed rigidly onto the tube; TPU compliance is
    approximated by the soft foot-contact solref (sim_env softens it 3x).
    Contact = sphere of the boot's outer radius on the tibia centerline,
    surface tangent at the kinematic tip x = TIBIA.  Since the Aug 19
    2026 dome boot the printed tip is this exact hemisphere.
    """
    return (
        f'            <body name="L{i}_pad" '
        f'pos="{BOOT_TIP_CTR:.5f} 0 0">\n'
        f'              <inertial pos="0 0 0" mass="0.004" '
        f'diaginertia="0.000001 0.000001 0.000001"/>\n'
        f'              <geom class="foot" name="L{i}_foot" type="sphere" '
        f'size="{FOOT_R:.5f}"/>\n'
        f'              <site name="L{i}_foot_site" pos="0 0 0" '
        f'size="0.018" group="4" rgba="1 1 1 0.05"/>\n'
        f'            </body>'
    )


def _leg_xml(i: int, x: float, y: float, z: float, qw: float, qz: float) -> str:
    # Tibia ground-collision capsule runs knee yoke -> boot socket; the
    # boot itself is already the L{i}_foot contact sphere.
    tibia_col_end = TIBIA - (HP.FOOT_BOOT_SOCKET_DEPTH + HP.FOOT_BOOT_TIP_L) * M
    hip_servo_xml = _hip_servo_visual_xml(i)
    knee_servo_xml = _knee_servo_visual_xml(i)
    coxa_link_xml = _coxa_link_visual_xml(i)
    femur_link_xml = _femur_link_visual_xml(i)
    tibia_link_xml = _tibia_link_visual_xml(i)
    # Joint ranges below were tightened after check_workspace_self_collision
    # in _verify_prototype.py found pose-dependent collisions between the
    # femur spar and the coxa_bracket flange (at large |yaw| + high femur
    # lift) and between coxa_link well / femur hip-pad and chassis_top.
    # These ranges MUST match the firmware (prototype_servo_bridge.ino) --
    # changing one without the other lets the policy command poses the
    # geometry cannot accommodate.
    #   yaw:   -0.61 .. +0.61 rad  (= +/-35 deg; was +/-0.90 = +/-51.6 deg)
    #   hip:   -1.40 .. +0.52 rad  (= -80.2 .. +30 deg; was -1.40 .. +0.85
    #                               = -80.2 .. +48.7 deg)
    #   knee:  -0.35 .. +2.62 rad  (= -20.1 .. +150 deg; Aug 2026: operator
    #                               widened from +80.2 deg — the tight cap
    #                               made the plant pose the bottom of the
    #                               fixed-feet envelope so the robot could
    #                               not crouch at all. Self-collision risk
    #                               above ~106 deg is at large |yaw| + full
    #                               hip retraction only; firmware limits
    #                               must be updated to match before any
    #                               hardware deploy of a crouching policy.)
    return f"""      <body name="L{i}_yaw" pos="{x:.5f} {y:.5f} {z:.5f}" quat="{qw:.6f} 0 0 {qz:.6f}">
        <inertial pos="{COXA / 2:.5f} 0 0" mass="{COXA_MASS}" diaginertia="0.00005 0.00006 0.00006"/>
        <joint name="L{i}_yaw" type="hinge" axis="0 0 1" range="-0.61 0.61"/>
{coxa_link_xml}
{hip_servo_xml}

        <body name="L{i}_femur" pos="{COXA:.5f} {HIP_ANCHOR_Y:.5f} 0">
          <inertial pos="{FEMUR / 2:.5f} 0 0" mass="{FEMUR_MASS}" diaginertia="0.00008 0.00022 0.00022"/>
          <joint name="L{i}_pitch" type="hinge" axis="0 1 0" range="-1.40 0.52"/>
          <geom class="legcol" name="L{i}_femur_col" type="capsule" fromto="0 0 0 {FEMUR:.5f} 0 0" size="0.010"/>
          <geom class="legcol" name="L{i}_knee_servo_col" type="box" pos="{FEMUR - 0.010:.5f} -0.026 0" size="0.021 0.011 0.020"/>
{femur_link_xml}
{knee_servo_xml}

          <body name="L{i}_tibia" pos="{FEMUR:.5f} 0 0">
            <inertial pos="{TIBIA / 2:.5f} 0 0" mass="{TIBIA_MASS}" diaginertia="0.00006 0.00022 0.00022"/>
            <joint name="L{i}_knee" type="hinge" axis="0 1 0" range="-0.35 2.62"/>
            <geom class="legcol" name="L{i}_tibia_col" type="capsule" fromto="0 0 0 {tibia_col_end:.5f} 0 0" size="0.008"/>
{tibia_link_xml}
{_foot_boot_body_xml(i)}
          </body>
        </body>
      </body>
"""


def _leg_actuators(i: int) -> str:
    return f"""    <position name="L{i}_yaw" joint="L{i}_yaw" kp="{KP_YAW}" forcerange="-{TORQUE_LIMIT} {TORQUE_LIMIT}"/>
    <position name="L{i}_pitch" joint="L{i}_pitch" kp="{KP_PITCH}" forcerange="-{TORQUE_LIMIT} {TORQUE_LIMIT}"/>
    <position name="L{i}_knee" joint="L{i}_knee" kp="{KP_KNEE}" forcerange="-{TORQUE_LIMIT} {TORQUE_LIMIT}"/>
    <velocity name="L{i}_yaw_d" joint="L{i}_yaw" kv="{DAMP_YAW}" forcerange="-{TORQUE_LIMIT} {TORQUE_LIMIT}"/>
    <velocity name="L{i}_pitch_d" joint="L{i}_pitch" kv="{DAMP_PITCH}" forcerange="-{TORQUE_LIMIT} {TORQUE_LIMIT}"/>
    <velocity name="L{i}_knee_d" joint="L{i}_knee" kv="{DAMP_KNEE}" forcerange="-{TORQUE_LIMIT} {TORQUE_LIMIT}"/>
"""


def _leg_sensors(i: int) -> str:
    return f"""    <jointpos name="L{i}_yaw_p" joint="L{i}_yaw"/>
    <jointpos name="L{i}_pitch_p" joint="L{i}_pitch"/>
    <jointpos name="L{i}_knee_p" joint="L{i}_knee"/>
    <touch name="L{i}_foot_t" site="L{i}_foot_site"/>
"""


def build_world(
    *,
    terrain_seed: int = 0,
    terrain_enabled: bool = True,
    obstacle_count: int = 8,
    obstacle_seed: int = 0,
    ensure_rider: bool = False,
):
    del ensure_rider
    if terrain_enabled:
        heights = make_terrain_heightmap(seed=terrain_seed)
    else:
        heights = np.zeros((HFIELD_NROW, HFIELD_NCOL), dtype=np.float32)
    obstacles_xml = make_obstacles_xml(heights, count=obstacle_count, seed=obstacle_seed)
    model = mujoco.MjModel.from_xml_string(build_xml(obstacles_xml=obstacles_xml))
    data = mujoco.MjData(model)
    _populate_hfield(model, heights)
    return model, data, heights


def _leg_ik(target_xyz_in_yaw_frame):
    u = float(target_xyz_in_yaw_frame[0]) - COXA
    w = -float(target_xyz_in_yaw_frame[2])
    L = math.hypot(u, w)
    if L > FEMUR + TIBIA - 1e-6 or L < abs(FEMUR - TIBIA) + 1e-6:
        return None
    cos_pt = (L * L - FEMUR * FEMUR - TIBIA * TIBIA) / (2 * FEMUR * TIBIA)
    cos_pt = max(-1.0, min(1.0, cos_pt))
    pt = math.acos(cos_pt)
    p = math.atan2(w, u) - math.atan2(TIBIA * math.sin(pt), FEMUR + TIBIA * math.cos(pt))
    return p, pt


class TripodGait:
    MAX_VX = 0.28
    MAX_VY = 0.20
    MAX_OMEGA = 1.0
    SCALE_PERIOD_MIN = 0.40
    SCALE_PERIOD_MAX = 2.00
    SCALE_LIFT_MIN = 0.30
    SCALE_LIFT_MAX = 2.50
    SCALE_STRIDE_MIN = 0.30
    SCALE_STRIDE_MAX = 1.80

    STANCE_RADIUS_SCALE_MIN = 0.55
    STANCE_RADIUS_SCALE_MAX = 1.05

    def __init__(
        self,
        *,
        period: float = 0.65,
        lift: float = 0.025,
        ramp: float = 0.35,
        vx: float = 0.0,
        vy: float = 0.0,
        omega: float = 0.0,
        period_scale: float = 1.0,
        lift_scale=1.0,
        stride_scale: float = 1.0,
        stance_radius_scale: float = 1.0,
    ):
        self.period = period
        self.lift = lift
        self.ramp = max(ramp, 1e-3)
        self.vx = vx
        self.vy = vy
        self.omega = omega
        self.period_scale = period_scale
        self.lift_scale = self._broadcast_lift(lift_scale)
        self.stride_scale = stride_scale
        self.leg_angles = [(i + 0.5) * math.pi / 3.0 for i in range(6)]
        p, pt = STANCE_FEMUR, STANCE_FEMUR + STANCE_TIBIA
        self.foot_neutral_x = COXA + FEMUR * math.cos(p) + TIBIA * math.cos(pt)
        self.foot_neutral_z = -FEMUR * math.sin(p) - TIBIA * math.sin(pt)
        self._foot_radius = LEG_RADIAL + self.foot_neutral_x
        self.stance_radius_scale = float(np.clip(
            stance_radius_scale,
            self.STANCE_RADIUS_SCALE_MIN,
            self.STANCE_RADIUS_SCALE_MAX,
        ))
        self._foot_radius_eff = self._foot_radius * self.stance_radius_scale
        self._phase_offset = math.pi / 2.0
        self._fallback = (0.0, STANCE_FEMUR, STANCE_TIBIA)
        self._vx_smooth = vx
        self._vy_smooth = vy
        self._om_smooth = omega
        self._last_t = None
        self._phase = 0.0
        self._elapsed = 0.0

    def set_velocity(self, *, vx=None, vy=None, omega=None):
        if vx is not None:
            self.vx = max(-self.MAX_VX, min(self.MAX_VX, float(vx)))
        if vy is not None:
            self.vy = max(-self.MAX_VY, min(self.MAX_VY, float(vy)))
        if omega is not None:
            self.omega = max(-self.MAX_OMEGA, min(self.MAX_OMEGA, float(omega)))

    def _broadcast_lift(self, lift_scale) -> np.ndarray:
        arr = np.asarray(lift_scale, dtype=np.float64)
        if arr.ndim == 0:
            arr = np.full(6, float(arr))
        elif arr.shape != (6,):
            raise ValueError(f"lift_scale must be scalar or length-6, got {arr.shape}")
        return np.clip(arr, self.SCALE_LIFT_MIN, self.SCALE_LIFT_MAX)

    def set_scales(self, *, period_scale=None, lift_scale=None, stride_scale=None):
        if period_scale is not None:
            self.period_scale = float(np.clip(period_scale, self.SCALE_PERIOD_MIN, self.SCALE_PERIOD_MAX))
        if lift_scale is not None:
            self.lift_scale = self._broadcast_lift(lift_scale)
        if stride_scale is not None:
            self.stride_scale = float(np.clip(stride_scale, self.SCALE_STRIDE_MIN, self.SCALE_STRIDE_MAX))

    def set_stance_radius_scale(self, scale: float) -> None:
        self.stance_radius_scale = float(np.clip(
            scale, self.STANCE_RADIUS_SCALE_MIN, self.STANCE_RADIUS_SCALE_MAX,
        ))
        self._foot_radius_eff = self._foot_radius * self.stance_radius_scale

    def neutral_pose(self) -> tuple:
        yaws = np.zeros(6)
        pitches = np.full(6, STANCE_FEMUR)
        knees = np.full(6, STANCE_TIBIA)
        for i, a in enumerate(self.leg_angles):
            fx_b = self._foot_radius_eff * math.cos(a)
            fy_b = self._foot_radius_eff * math.sin(a)
            yaw_origin_x = LEG_RADIAL * math.cos(a)
            yaw_origin_y = LEG_RADIAL * math.sin(a)
            rx = fx_b - yaw_origin_x
            ry = fy_b - yaw_origin_y
            ca, sa = math.cos(a), math.sin(a)
            x_yaw = ca * rx + sa * ry
            y_yaw = -sa * rx + ca * ry
            yaw_angle = math.atan2(y_yaw, x_yaw)
            r_planar = math.hypot(x_yaw, y_yaw)
            ik = _leg_ik((r_planar, 0.0, self.foot_neutral_z))
            if ik is None:
                continue
            p, pt = ik
            yaws[i] = yaw_angle
            pitches[i] = p
            knees[i] = pt
        return yaws, pitches, knees

    def swing_mask(self) -> np.ndarray:
        out = np.zeros(6, dtype=np.float64)
        for i in range(6):
            tripod = 0 if i % 2 == 0 else 1
            phi = (self._phase + self._phase_offset + tripod * math.pi) % (2 * math.pi)
            out[i] = 1.0 if phi < math.pi else 0.0
        return out

    def reset_phase(self, *, phase: float = 0.0, t: float = 0.0):
        self._phase = phase % (2 * math.pi)
        self._elapsed = 0.0
        self._last_t = t
        self._vx_smooth = self.vx
        self._vy_smooth = self.vy
        self._om_smooth = self.omega

    def stop(self):
        self.set_velocity(vx=0.0, vy=0.0, omega=0.0)

    def _advance(self, t: float):
        if self._last_t is None:
            self._last_t = t
            return 0.0
        dt = max(0.0, t - self._last_t)
        self._last_t = t
        self._elapsed += dt
        self._phase = (self._phase + 2 * math.pi * dt / max(self.period * self.period_scale, 0.05)) % (2 * math.pi)
        return dt

    def _smoothed_command(self, dt: float):
        if dt <= 0.0:
            return self._vx_smooth, self._vy_smooth, self._om_smooth
        tau = 0.15
        a = 1.0 - math.exp(-dt / tau)
        self._vx_smooth += a * (self.vx - self._vx_smooth)
        self._vy_smooth += a * (self.vy - self._vy_smooth)
        self._om_smooth += a * (self.omega - self._om_smooth)
        return self._vx_smooth, self._vy_smooth, self._om_smooth

    def _foot_target_in_body(self, i: int, vx, vy, omega):
        t_eff = max(self.period * self.period_scale, 0.05)
        ramp_amp = min(self._elapsed / self.ramp, 1.0)
        tripod = 0 if i % 2 == 0 else 1
        phi = (self._phase + self._phase_offset + tripod * math.pi) % (2 * math.pi)
        if phi < math.pi:
            s = phi / math.pi
            prog = -0.5 + s
            dz = self.lift * float(self.lift_scale[i]) * ramp_amp * math.sin(math.pi * s)
        else:
            s = (phi - math.pi) / math.pi
            prog = 0.5 - s
            dz = 0.0
        a_i = self.leg_angles[i]
        sa, ca = math.sin(a_i), math.cos(a_i)
        v_x_at = vx - omega * self._foot_radius_eff * sa
        v_y_at = vy + omega * self._foot_radius_eff * ca
        dx = prog * v_x_at * t_eff / 2.0 * ramp_amp * self.stride_scale
        dy = prog * v_y_at * t_eff / 2.0 * ramp_amp * self.stride_scale
        return dx, dy, dz

    def desired(self, t: float):
        dt = self._advance(t)
        vx, vy, omega = self._smoothed_command(dt)
        yaws = np.zeros(6)
        pitches = np.full(6, STANCE_FEMUR)
        knees = np.full(6, STANCE_TIBIA)
        for i, a in enumerate(self.leg_angles):
            dx_b, dy_b, dz_b = self._foot_target_in_body(i, vx, vy, omega)
            fx_b_neutral = self._foot_radius_eff * math.cos(a)
            fy_b_neutral = self._foot_radius_eff * math.sin(a)
            fx_b = fx_b_neutral + dx_b
            fy_b = fy_b_neutral + dy_b
            yaw_origin_x = LEG_RADIAL * math.cos(a)
            yaw_origin_y = LEG_RADIAL * math.sin(a)
            rx = fx_b - yaw_origin_x
            ry = fy_b - yaw_origin_y
            ca, sa = math.cos(a), math.sin(a)
            x_yaw = ca * rx + sa * ry
            y_yaw = -sa * rx + ca * ry
            yaw_angle = math.atan2(y_yaw, x_yaw)
            r_planar = math.hypot(x_yaw, y_yaw)
            ik = _leg_ik((r_planar, 0.0, self.foot_neutral_z + dz_b))
            if ik is None:
                yaws[i], pitches[i], knees[i] = self._fallback
            else:
                p, k = ik
                yaws[i], pitches[i], knees[i] = yaw_angle, p, k
        return yaws, pitches, knees


def _set_targets(model: mujoco.MjModel, data: mujoco.MjData, yaws, pitches, knees):
    for i in range(6):
        base = i * 6
        data.ctrl[base + 0] = yaws[i]
        data.ctrl[base + 1] = pitches[i]
        data.ctrl[base + 2] = knees[i]


def _initial_pose(data: mujoco.MjData):
    for i in range(6):
        base = i * 6
        data.ctrl[base + 0] = 0.0
        data.ctrl[base + 1] = STANCE_FEMUR
        data.ctrl[base + 2] = STANCE_TIBIA


def _populate_hfield(model: mujoco.MjModel, heights: np.ndarray):
    hf_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_HFIELD, "terrain")
    nrow = int(model.hfield_nrow[hf_id])
    ncol = int(model.hfield_ncol[hf_id])
    start = int(model.hfield_adr[hf_id])
    model.hfield_data[start:start + nrow * ncol] = np.asarray(heights, dtype=np.float32).reshape(nrow, ncol).flatten()


def _set_stance_qpos(model: mujoco.MjModel, data: mujoco.MjData):
    data.qpos[0:3] = [0.0, 0.0, stance_chassis_height()]
    data.qpos[3:7] = [1.0, 0.0, 0.0, 0.0]
    for i in range(6):
        for kind, val in (("yaw", 0.0), ("pitch", STANCE_FEMUR), ("knee", STANCE_TIBIA)):
            j = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, f"L{i}_{kind}")
            data.qpos[model.jnt_qposadr[j]] = val
    data.qvel[:] = 0.0
    mujoco.mj_forward(model, data)


def run_headless(model, data, gait: TripodGait, *, duration: float, settle: float = 0.8, run_gait: bool = True):
    _set_stance_qpos(model, data)
    chassis = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "chassis")
    for _ in range(int(settle / model.opt.timestep)):
        _initial_pose(data)
        mujoco.mj_step(model, data)
    p0 = np.array(data.body(chassis).xpos)
    for k in range(int(duration / model.opt.timestep)):
        if run_gait:
            y, p, kn = gait.desired(k * model.opt.timestep)
            _set_targets(model, data, y, p, kn)
        else:
            _initial_pose(data)
        mujoco.mj_step(model, data)
    p1 = np.array(data.body(chassis).xpos)
    d = p1 - p0
    print(f"  chassis after settle: pos = {p0} m")
    print(f"  chassis after walk:   pos = {p1} m")
    print(f"  Δposition = ({d[0]:+.3f}, {d[1]:+.3f}, {d[2]:+.3f}) m")
    print(f"  horizontal travel = {math.hypot(d[0], d[1]):.3f} m in {duration:.2f}s")


def run_viewer(model, data, gait: TripodGait, *, run_gait: bool = True, settle: float = 0.8):
    import mujoco.viewer as viewer

    def reset():
        _set_stance_qpos(model, data)

    reset()
    with viewer.launch_passive(model, data) as v:
        # Force body-name labels on by default so the per-part-type
        # palette is searchable at a glance.  Users can still toggle
        # them off at runtime with the viewer's ``B`` shortcut.
        try:
            v.opt.label = mujoco.mjtLabel.mjLABEL_BODY
        except Exception:
            pass
        t0 = data.time
        while v.is_running():
            t = data.time - t0
            if data.time < settle or not run_gait:
                _initial_pose(data)
            else:
                y, p, kn = gait.desired(t - settle)
                _set_targets(model, data, y, p, kn)
            mujoco.mj_step(model, data)
            v.sync()
            time.sleep(max(0.0, model.opt.timestep - 1e-4))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--headless", action="store_true")
    ap.add_argument("--duration", type=float, default=6.0)
    ap.add_argument("--period", type=float, default=0.65)
    ap.add_argument("--lift", type=float, default=0.025)
    ap.add_argument("--vx", type=float, default=0.10)
    ap.add_argument("--vy", type=float, default=0.0)
    ap.add_argument("--omega", type=float, default=0.0)
    ap.add_argument("--no-gait", action="store_true")
    ap.add_argument("--no-terrain", action="store_true")
    ap.add_argument("--terrain-seed", type=int, default=0)
    ap.add_argument("--obstacles", type=int, default=6)
    ap.add_argument("--obstacle-seed", type=int, default=0)
    ap.add_argument("--dump-xml", default=None)
    args = ap.parse_args()

    heights = np.zeros((HFIELD_NROW, HFIELD_NCOL), dtype=np.float32) if args.no_terrain else make_terrain_heightmap(args.terrain_seed)
    obstacles_xml = make_obstacles_xml(heights, count=args.obstacles, seed=args.obstacle_seed)
    xml = build_xml(obstacles_xml=obstacles_xml)
    if args.dump_xml:
        with open(args.dump_xml, "w") as f:
            f.write(xml)
        print(f"Wrote {args.dump_xml}")
        return
    model = mujoco.MjModel.from_xml_string(xml)
    data = mujoco.MjData(model)
    _populate_hfield(model, heights)
    print(f"Prototype stance height = {stance_chassis_height():.3f} m")
    print(f"Loaded MuJoCo model: nq={model.nq} nv={model.nv} nu={model.nu} nbody={model.nbody}")
    gait = TripodGait(period=args.period, lift=args.lift, vx=args.vx, vy=args.vy, omega=args.omega)
    if args.headless:
        run_headless(model, data, gait, duration=args.duration, run_gait=not args.no_gait)
    else:
        run_viewer(model, data, gait, run_gait=not args.no_gait)


if __name__ == "__main__":
    main()
