"""Leg-odometry velocity estimator tests (rl_move/estimator.py).

Ground truth comes from the kinematics themselves: joint trajectories
are GENERATED by IK for a body moving at a known velocity over
world-pinned feet, then the estimator must recover that velocity from
the joint angles alone. Every case exercises code that exists
independently of the estimator (body_ik FK/IK), so a sign or frame
error here cannot self-confirm.
"""
from __future__ import annotations

import copy
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "linux_control"))
sys.path.insert(0, str(ROOT / "linux_control" / "urt2_setup"))

from rl_move.body_ik import (  # noqa: E402
    fk_all_feet, ik_leg_from_foot_body, leg_azimuths, rot_z,
)
from rl_move.estimator import LegOdometryVelocity, integrate_track  # noqa: E402

DT = 0.04  # 25 Hz, the control rate everywhere in this stack
DEG = math.pi / 180.0

# Crouch-plant base pose: yaw 0, hip +25 deg, knee +70 deg per leg —
# feet tucked in with xy reach margin, so small body glides stay
# IK-reachable (a long glide on pinned feet is not; robots step).
Q0 = np.tile([0.0, 25.0 * DEG, 70.0 * DEG], 6)


def _q_from_feet(feet_body: np.ndarray) -> np.ndarray:
    q = np.zeros(18)
    for i, az in enumerate(leg_azimuths()):
        sol = ik_leg_from_foot_body(feet_body[i], az)
        assert sol is not None, f"leg {i} unreachable in test trajectory"
        q[3 * i:3 * i + 3] = sol
    return q


def test_fk_ik_roundtrip():
    feet = fk_all_feet(Q0)
    q = _q_from_feet(feet)
    assert np.allclose(q, Q0, atol=1e-6)


def test_pure_translation_recovered():
    v_true = np.array([0.05, -0.02])
    p0 = fk_all_feet(Q0)
    est = LegOdometryVelocity(dt=DT)
    zeros3 = np.zeros(3)
    vals = []
    for k in range(30):  # 1.2 s -> ~65 mm drift, inside reach margin
        feet = p0.copy()
        feet[:, :2] -= v_true * (k * DT)   # body glides -> feet drift back
        v = est.update(_q_from_feet(feet), zeros3, 0.0, 0.0)
        if k >= 15:                        # past the low-pass settle
            vals.append(v)
    v_mean = np.mean(vals, axis=0)
    assert np.allclose(v_mean, v_true, atol=0.005), v_mean


def test_pure_yaw_rotation_reads_zero_translation():
    # Body spins at wz over pinned feet: the gyro cross-term must cancel
    # the FK differencing term, leaving ~zero translational velocity.
    wz = 0.4
    p0 = fk_all_feet(Q0)
    est = LegOdometryVelocity(dt=DT)
    gyro = np.array([0.0, 0.0, wz])
    vals = []
    for k in range(50):
        feet = (rot_z(-wz * k * DT) @ p0.T).T
        v = est.update(_q_from_feet(feet), gyro, 0.0, 0.0)
        if k >= 25:
            vals.append(np.hypot(*v))
    assert max(vals) < 0.01, max(vals)


def test_swing_legs_rejected():
    # Tripod reality: half the feet are in the air doing arbitrary
    # things. Legs 1 and 4 lift 30 mm and wobble; the estimate must
    # come from the planted four and still recover the body velocity.
    v_true = np.array([0.04, 0.03])
    p0 = fk_all_feet(Q0)
    est = LegOdometryVelocity(dt=DT)
    zeros3 = np.zeros(3)
    vals = []
    for k in range(30):
        t = k * DT
        feet = p0.copy()
        feet[:, :2] -= v_true * t
        for leg in (1, 4):
            feet[leg, 2] += 0.030
            feet[leg, 0] += 0.020 * math.sin(2 * math.pi * t)
            feet[leg, 1] += 0.015 * math.cos(2 * math.pi * t)
        v = est.update(_q_from_feet(feet), zeros3, 0.0, 0.0)
        if k >= 15:
            vals.append(v)
    v_mean = np.mean(vals, axis=0)
    assert np.allclose(v_mean, v_true, atol=0.008), v_mean


def test_stationary_under_encoder_noise():
    # DR worst case: 0.5 deg gaussian encoder noise on a standing robot.
    # The filtered estimate must not hallucinate motion above ~2 cm/s
    # (commands live at 5-15 cm/s).
    rng = np.random.default_rng(7)
    est = LegOdometryVelocity(dt=DT)
    zeros3 = np.zeros(3)
    vals = []
    for k in range(100):
        q = Q0 + rng.normal(0.0, 0.5 * DEG, 18)
        v = est.update(q, zeros3, 0.0, 0.0)
        if k >= 25:
            vals.append(np.hypot(*v))
    assert float(np.mean(vals)) < 0.02, np.mean(vals)


def test_first_tick_and_reset_return_zero():
    est = LegOdometryVelocity(dt=DT)
    assert np.allclose(est.update(Q0, np.zeros(3), 0.0, 0.0), 0.0)
    est.update(Q0 + 0.05, np.zeros(3), 0.0, 0.0)
    est.reset()
    assert np.allclose(est.update(Q0, np.zeros(3), 0.0, 0.0), 0.0)


def test_deepcopy_snapshot_safe():
    # MJX pooled resets snapshot per-episode state with copy.deepcopy;
    # the estimator must survive that with independent state.
    p0 = fk_all_feet(Q0)

    def q_at(k):
        feet = p0.copy()
        feet[:, :2] -= np.array([0.05, 0.0]) * (k * DT)
        return _q_from_feet(feet)

    est = LegOdometryVelocity(dt=DT)
    est.update(q_at(0), np.zeros(3), 0.0, 0.0)
    est.update(q_at(1), np.zeros(3), 0.0, 0.0)
    snap = copy.deepcopy(est)
    est.update(q_at(2), np.zeros(3), 0.0, 0.0)
    assert not np.allclose(snap._v_filt, est._v_filt)
    v_a = snap.update(q_at(2), np.zeros(3), 0.0, 0.0)
    assert np.all(np.isfinite(v_a))


def _tripod_feet(t: float, v: np.ndarray, p0: np.ndarray,
                 cycle: float = 1.2, lift: float = 0.030) -> np.ndarray:
    """Idealized tripod walk: body moves at v; each tripod alternates
    stance (foot pinned in world, drifting back through the body frame)
    and swing (foot lifted `lift`, flying forward to its next anchor).
    Anchors lead by half a stance drift so feet oscillate around p0."""
    half = cycle / 2.0
    feet = np.zeros_like(p0)
    for leg in range(6):
        tri = leg % 2                       # tripod A = legs 0,2,4
        local = (t + tri * half) % cycle    # 0..cycle within leg's cycle
        lead = v * half / 2.0
        if local < half:                    # stance: pinned, drifts back
            feet[leg, :2] = p0[leg, :2] + lead - v * local
            feet[leg, 2] = p0[leg, 2]
        else:                               # swing: lifted, flies forward
            s = (local - half) / half       # 0..1 through the swing
            feet[leg, :2] = (p0[leg, :2] - lead) + v * half * s
            feet[leg, 2] = p0[leg, 2] + lift * math.sin(math.pi * s)
    return feet


def test_integrate_track_tripod_walk():
    # Offline helper (tape-measure validation path): a 12 s idealized
    # tripod walk at 0.03 m/s sampled at an irregular ~3.3 Hz like the
    # hardware telemetry logger. Swing feet are lifted, so the stance
    # mask must reject them and the integrated distance come out near
    # v * T despite the coarse aliased sampling.
    rng = np.random.default_rng(3)
    v_true = np.array([0.03, 0.0])
    p0 = fk_all_feet(Q0)
    t, rows, ts = 0.0, [], []
    while t < 12.0:
        rows.append(_q_from_feet(_tripod_feet(t, v_true, p0)) / DEG)
        ts.append(t)
        t += 0.30 + rng.uniform(-0.03, 0.03)
    out = integrate_track(np.array(rows), np.array(ts))
    want = 0.03 * out["duration_s"]
    assert abs(out["disp_along_m"] - want) < 0.35 * want, out
