"""Render the auto-derived fastener BOM table.

Reads ``fastener_registry.build_all_fastener_instances()``, aggregates
the rows into a markdown table, and prints it to stdout.  Wired into
the Makefile as ``make bom-fasteners``.  ``make check-cad-fast``
appends the same table to the end of its report.

The BOM table is intentionally a SINGLE source of truth: edit the
registry, NOT the markdown file.  ``hexapod_walker/prototype/PROTOTYPE_BOM.md``
and ``SHOPPING_LIST.md`` carry a Fasteners section bracketed by
``<!-- BEGIN FASTENERS -->`` / ``<!-- END FASTENERS -->`` markers
that the ``--inject PATH`` mode rewrites in place.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.abspath(os.path.join(HERE, ".."))
if PROTO not in sys.path:
    sys.path.insert(0, PROTO)

import fastener_registry  # noqa: E402


BEGIN = "<!-- BEGIN FASTENERS (auto-generated by scripts/render_fastener_bom.py) -->"
END   = "<!-- END FASTENERS -->"


def render_table() -> str:
    rows = fastener_registry.fastener_bom_rows()
    lines = []
    lines.append("| Spec | McMaster P/N | Qty | Used in |")
    lines.append("|------|--------------|-----|---------|")
    total = 0
    for spec, pn, qty, used in rows:
        lines.append(f"| {spec} | {pn} | {qty} | {used} |")
        total += qty
    lines.append(f"|  |  | **{total}** | **total fasteners** |")
    return "\n".join(lines)


def render_section() -> str:
    body = render_table()
    return (
        f"{BEGIN}\n"
        "\n"
        "## Fasteners\n"
        "\n"
        "Auto-derived from `fastener_registry.build_all_fastener_instances()`.\n"
        "Edit the registry (not this table) and re-run `make bom-fasteners`.\n"
        "\n"
        f"{body}\n"
        "\n"
        "Notes:\n"
        "- Cradle servo mounts (Design E mixed-mode, May 2026): each\n"
        "  cradle has 4 bolts driven VERTICALLY from above each servo\n"
        "  ear.  The 2 -X bolts thread into an M3 brass heat-set\n"
        "  insert (`94459A130`) in a Phi 4 mm pocket inside a Phi 8 mm\n"
        "  printed boss (36 such bolts = 2 -X x 3 cradles x 6 legs);\n"
        "  the 2 +X bolts self-tap into a bare Phi 2.5 mm pilot\n"
        "  drilled into the well wall (36 such bolts = 2 +X x 3\n"
        "  cradles x 6 legs).  The +X column reverted to self-tap\n"
        "  because the Phi 8 mm heat-set boss footprint cannot coexist\n"
        "  with the +X wire-exit channel that the servo's molded\n"
        "  wire boot must pass through during insertion -- see\n"
        "  ``hexapod_prototype.INSERT_M3_SELFTAP_*`` for the design\n"
        "  decision and ``_verify_prototype.check_servo_insertion_\n"
        "  path`` for the regression probe that catches the\n"
        "  boot-vs-wall collision.\n"
        "- Heat-set inserts (36 x `94459A130`) are pressed in BEFORE\n"
        "  the servo cradle is mated to its neighbour: heat the insert\n"
        "  with a soldering iron at ~220 deg C, drop it into the\n"
        "  printed Phi 4 mm x 6 mm pocket, apply light downward\n"
        "  pressure for ~10-15 s until the knurl displaces plastic\n"
        "  into the boss wall, then cool ~30 s before threading the\n"
        "  M3 x 8 SHCS in.  The 2 +X bolts per cradle bite directly\n"
        "  into the printed plastic and do NOT use a heat-set insert.\n"
        "- Link-to-X-horn bolts (72 x M2x8 SHCS / `91290A005`) self-tap into\n"
        "  the plastic 4-arm X-horn's existing Phi ~ 2.0 mm M2-sized untapped\n"
        "  arm holes (May 2026 fastener-spec fix: the X-horn arms are NOT\n"
        "  M3-sized -- an M3 SHCS won't fit through them).  Optional thread-\n"
        "  forming upgrade: McMaster `99461A340` (M2x8 thread-form for\n"
        "  plastic).  See `fasteners/README.md` for the full rationale.\n"
        "- Captive nyloc nuts are still used at the foot-pad hinge pins (6)\n"
        "  and at the coxa-bracket-to-chassis bolts (24); both joints have\n"
        "  through-hole bolts with the nut on the opposite side.\n"
        "- The M2.5 spline center screw ships with each DS3225-class servo --\n"
        "  it's listed here so the screwdriver-access verifier check knows the\n"
        "  fastener exists, but you do NOT order it separately.\n"
        "- See `fasteners/README.md` for the McMaster STEP swap-in flow if you\n"
        "  want to replace the parametric fallback geometry with real CAD.\n"
        "\n"
        f"{END}\n"
    )


def inject_into(path: str) -> bool:
    """Rewrite the BEGIN/END section in ``path`` in place.  Returns
    True on success, False if the markers are missing (in which case
    the caller should append the section manually)."""
    with open(path, "r") as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        return False
    pre, _, rest = text.partition(BEGIN)
    _, _, post = rest.partition(END)
    new = pre + render_section().rstrip() + post
    if new != text:
        with open(path, "w") as f:
            f.write(new)
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Print the auto-derived fastener BOM markdown table, or "
            "inject it into a markdown file between the "
            "<!-- BEGIN FASTENERS --> / <!-- END FASTENERS --> markers."
        ),
    )
    ap.add_argument(
        "--inject",
        metavar="PATH",
        action="append",
        default=[],
        help=(
            "Rewrite the BOM section in PATH in place.  Repeat to "
            "update multiple files at once."
        ),
    )
    args = ap.parse_args(argv)
    if args.inject:
        ok = True
        for path in args.inject:
            if not inject_into(path):
                print(f"render_fastener_bom: no <!-- BEGIN FASTENERS --> "
                      f"marker in {path}; section not updated",
                      file=sys.stderr)
                ok = False
            else:
                print(f"render_fastener_bom: updated {path}")
        return 0 if ok else 1
    print(render_section())
    return 0


if __name__ == "__main__":
    sys.exit(main())
