"""Render the auto-derived fastener BOM table.

Reads ``fastener_registry.build_all_fastener_instances()``, aggregates
the rows into a markdown table, and prints it to stdout.  Wired into
the Makefile as ``make bom-fasteners``.  ``make check-cad-fast``
appends the same table to the end of its report.

The BOM table is intentionally a SINGLE source of truth: edit the
registry, NOT the markdown file.  ``hexapod_walker/prototype/PROTOTYPE_BOM.md``
and ``SHOPPING_LIST.md`` carry a Fasteners section bracketed by
``<!-- BEGIN FASTENERS -->`` / ``<!-- END FASTENERS -->`` markers
that the ``--inject PATH`` mode rewrites in place.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.abspath(os.path.join(HERE, ".."))
if PROTO not in sys.path:
    sys.path.insert(0, PROTO)

import fastener_registry  # noqa: E402


BEGIN = "<!-- BEGIN FASTENERS (auto-generated by scripts/render_fastener_bom.py) -->"
END   = "<!-- END FASTENERS -->"


def render_table() -> str:
    rows = fastener_registry.fastener_bom_rows()
    lines = []
    lines.append("| Spec | McMaster P/N | Qty | Used in |")
    lines.append("|------|--------------|-----|---------|")
    total = 0
    for spec, pn, qty, used in rows:
        lines.append(f"| {spec} | {pn} | {qty} | {used} |")
        total += qty
    lines.append(f"|  |  | **{total}** | **total fasteners** |")
    return "\n".join(lines)


def render_section() -> str:
    body = render_table()
    return (
        f"{BEGIN}\n"
        "\n"
        "## Fasteners\n"
        "\n"
        "Auto-derived from `fastener_registry.build_all_fastener_instances()`.\n"
        "Edit the registry (not this table) and re-run `make bom-fasteners`.\n"
        "\n"
        f"{body}\n"
        "\n"
        "Notes:\n"
        "- Cradle servo mounts (72 of the M3x8 SHCS) are driven VERTICALLY\n"
        "  from above each servo ear and self-tap into a printed Phi 2.5 mm\n"
        "  pilot hole in the cradle shelf below.  Existing M3 SHCS stock\n"
        "  (P/N 91290A113) doubles as the self-tapper -- the standard hobby-\n"
        "  servo mounting style; no separate self-tap SKU.\n"
        "- Captive nyloc nuts are still used at the foot-pad hinge pins (6)\n"
        "  and at the coxa-bracket-to-chassis bolts (24); both joints have\n"
        "  through-hole bolts with the nut on the opposite side.\n"
        "- The M2.5 spline center screw ships with each DS3225-class servo --\n"
        "  it's listed here so the screwdriver-access verifier check knows the\n"
        "  fastener exists, but you do NOT order it separately.\n"
        "- See `fasteners/README.md` for the McMaster STEP swap-in flow if you\n"
        "  want to replace the parametric fallback geometry with real CAD.\n"
        "\n"
        f"{END}\n"
    )


def inject_into(path: str) -> bool:
    """Rewrite the BEGIN/END section in ``path`` in place.  Returns
    True on success, False if the markers are missing (in which case
    the caller should append the section manually)."""
    with open(path, "r") as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        return False
    pre, _, rest = text.partition(BEGIN)
    _, _, post = rest.partition(END)
    new = pre + render_section().rstrip() + post
    if new != text:
        with open(path, "w") as f:
            f.write(new)
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Print the auto-derived fastener BOM markdown table, or "
            "inject it into a markdown file between the "
            "<!-- BEGIN FASTENERS --> / <!-- END FASTENERS --> markers."
        ),
    )
    ap.add_argument(
        "--inject",
        metavar="PATH",
        action="append",
        default=[],
        help=(
            "Rewrite the BOM section in PATH in place.  Repeat to "
            "update multiple files at once."
        ),
    )
    args = ap.parse_args(argv)
    if args.inject:
        ok = True
        for path in args.inject:
            if not inject_into(path):
                print(f"render_fastener_bom: no <!-- BEGIN FASTENERS --> "
                      f"marker in {path}; section not updated",
                      file=sys.stderr)
                ok = False
            else:
                print(f"render_fastener_bom: updated {path}")
        return 0 if ok else 1
    print(render_section())
    return 0


if __name__ == "__main__":
    sys.exit(main())
