"""Render the auto-derived fastener BOM table.

Reads ``fastener_registry.build_all_fastener_instances()``, aggregates
the rows into a markdown table, and prints it to stdout.  Wired into
the Makefile as ``make bom-fasteners``.  ``make check-cad-fast``
appends the same table to the end of its report.

The BOM table is intentionally a SINGLE source of truth: edit the
registry, NOT the markdown file.  ``hexapod_walker/prototype/PROTOTYPE_BOM.md``
and ``SHOPPING_LIST.md`` carry a Fasteners section bracketed by
``<!-- BEGIN FASTENERS -->`` / ``<!-- END FASTENERS -->`` markers
that the ``--inject PATH`` mode rewrites in place.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.abspath(os.path.join(HERE, ".."))
if PROTO not in sys.path:
    sys.path.insert(0, PROTO)

import fastener_registry  # noqa: E402


BEGIN = "<!-- BEGIN FASTENERS (auto-generated by scripts/render_fastener_bom.py) -->"
END   = "<!-- END FASTENERS -->"


def render_table() -> str:
    rows = fastener_registry.fastener_bom_rows()
    lines = []
    lines.append("| Spec | McMaster P/N | Qty | Used in |")
    lines.append("|------|--------------|-----|---------|")
    total = 0
    for spec, pn, qty, used in rows:
        lines.append(f"| {spec} | {pn} | {qty} | {used} |")
        total += qty
    lines.append(f"|  |  | **{total}** | **total fasteners** |")
    return "\n".join(lines)


def render_section() -> str:
    body = render_table()
    return (
        f"{BEGIN}\n"
        "\n"
        "## Fasteners\n"
        "\n"
        "Auto-derived from `fastener_registry.build_all_fastener_instances()`.\n"
        "Edit the registry (not this table) and re-run `make bom-fasteners`.\n"
        "\n"
        f"{body}\n"
        "\n"
        "Notes:\n"
        "- The servo OUTPUT face is reserved for the flush 20 mm disc\n"
        "  horn (no front-face mounting).  POSITIVE body retention bolts\n"
        "  into the servo's REAL END-face M2.5 holes: each STS3215 +/-X end\n"
        "  face carries a 10 x 10 mm square of 4 M2.5 case holes (measured\n"
        "  Waveshare ST3215).  The HIP and KNEE cradles each drive 4 x M2.5\n"
        "  x 8 SHCS through their -X wall into that square (`91290A104`, 4\n"
        "  per cradle x 2 cradles x 6 legs = 48; head recessed in a wall\n"
        "  counterbore, threads into the servo's own metal case).  The YAW\n"
        "  cradle takes NONE (Jun 2026 flush-horn refit): both yaw bearings\n"
        "  moving above the flush horn lowered the yaw output 5.5 mm, so the\n"
        "  servo now hangs ~20 mm below the -6 chassis floor and even its\n"
        "  upper end-face row clears no -X wall -- the yaw servo is held by\n"
        "  the `yaw_servo_retainer` strap + anchor bolts + output-face seat\n"
        "  instead.  These screws positively bolt the servo instead of only\n"
        "  gripping it; the hip/knee clamp cap is retained as secondary\n"
        "  capture.\n"
        "- Link-to-disc-horn bolts (120 total) thread into the 20 mm\n"
        "  aluminum 25T disc horn's M3 TAPPED holes on a 14 mm bolt\n"
        "  circle (cross pattern at 0/90/180/270 deg); the aluminum is\n"
        "  the thread-engagement medium -- no self-tap, no heat-set.\n"
        "  Two lengths (Jun 2026 flush-output refit): the DRIVEN hip +\n"
        "  knee front-horn bolts are **48 x M3x10 SHCS (`91290A114`)**\n"
        "  -- 2 mm longer because the flush output seats the driven\n"
        "  disc horn 2 mm lower, so the bolt traverses an extra pad\n"
        "  before the disc -- while the yaw front horn + the two\n"
        "  passive rear-boss horns stay **72 x M3x8 SHCS (`91290A113`)**.\n"
        "  (June 2026 disc-horn switch, retiring the now-retired plastic\n"
        "  4-arm X-horn's M2x8 self-tap scheme.)  See\n"
        "  `fasteners/README.md` for the full rationale.\n"
        "- Captive nyloc nuts are used at the foot-pad hinge pins (6 total,\n"
        "  one per leg); the through-hole bolt is captured by the nyloc on\n"
        "  the opposite side of the foot.  The previous 24 x M3 x 14\n"
        "  coxa-bracket-to-chassis nyloc'd through-bolts were retired in\n"
        "  the May 2026 chassis_bottom-integrated yaw cradle redesign --\n"
        "  the printed bracket flange they clamped is gone, replaced by\n"
        "  per-leg cradle bosses inside chassis_bottom.\n"
        "- The M2.5 spline center screw ships with each STS3215 servo --\n"
        "  it's listed here so the screwdriver-access verifier check knows the\n"
        "  fastener exists, but you do NOT order it separately.\n"
        "- See `fasteners/README.md` for the McMaster STEP swap-in flow if you\n"
        "  want to replace the parametric fallback geometry with real CAD.\n"
        "\n"
        f"{END}\n"
    )


def inject_into(path: str) -> bool:
    """Rewrite the BEGIN/END section in ``path`` in place.  Returns
    True on success, False if the markers are missing (in which case
    the caller should append the section manually)."""
    with open(path, "r") as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        return False
    pre, _, rest = text.partition(BEGIN)
    _, _, post = rest.partition(END)
    new = pre + render_section().rstrip() + post
    if new != text:
        with open(path, "w") as f:
            f.write(new)
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Print the auto-derived fastener BOM markdown table, or "
            "inject it into a markdown file between the "
            "<!-- BEGIN FASTENERS --> / <!-- END FASTENERS --> markers."
        ),
    )
    ap.add_argument(
        "--inject",
        metavar="PATH",
        action="append",
        default=[],
        help=(
            "Rewrite the BOM section in PATH in place.  Repeat to "
            "update multiple files at once."
        ),
    )
    args = ap.parse_args(argv)
    if args.inject:
        ok = True
        for path in args.inject:
            if not inject_into(path):
                print(f"render_fastener_bom: no <!-- BEGIN FASTENERS --> "
                      f"marker in {path}; section not updated",
                      file=sys.stderr)
                ok = False
            else:
                print(f"render_fastener_bom: updated {path}")
        return 0 if ok else 1
    print(render_section())
    return 0


if __name__ == "__main__":
    sys.exit(main())
