"""Render the auto-derived fastener BOM table.

Reads ``fastener_registry.build_all_fastener_instances()``, aggregates
the rows into a markdown table, and prints it to stdout.  Wired into
the Makefile as ``make bom-fasteners``.  ``make check-cad-fast``
appends the same table to the end of its report.

The BOM table is intentionally a SINGLE source of truth: edit the
registry, NOT the markdown file.  ``hexapod_walker/prototype/PROTOTYPE_BOM.md``
and ``SHOPPING_LIST.md`` carry a Fasteners section bracketed by
``<!-- BEGIN FASTENERS -->`` / ``<!-- END FASTENERS -->`` markers
that the ``--inject PATH`` mode rewrites in place.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.abspath(os.path.join(HERE, ".."))
if PROTO not in sys.path:
    sys.path.insert(0, PROTO)

import fastener_registry  # noqa: E402


BEGIN = "<!-- BEGIN FASTENERS (auto-generated by scripts/render_fastener_bom.py) -->"
END   = "<!-- END FASTENERS -->"


def render_table() -> str:
    rows = fastener_registry.fastener_bom_rows()
    lines = []
    lines.append("| Spec | McMaster P/N | Qty | Used in |")
    lines.append("|------|--------------|-----|---------|")
    total = 0
    for spec, pn, qty, used in rows:
        lines.append(f"| {spec} | {pn} | {qty} | {used} |")
        total += qty
    lines.append(f"|  |  | **{total}** | **total fasteners** |")
    return "\n".join(lines)


def render_section() -> str:
    body = render_table()
    return (
        f"{BEGIN}\n"
        "\n"
        "## Fasteners\n"
        "\n"
        "Auto-derived from `fastener_registry.build_all_fastener_instances()`.\n"
        "Edit the registry (not this table) and re-run `make bom-fasteners`.\n"
        "\n"
        f"{body}\n"
        "\n"
        "Notes:\n"
        "- The servo OUTPUT face is reserved for the flush 20 mm disc\n"
        "  horn (no front-face mounting).  POSITIVE body retention bolts\n"
        "  into the servo's REAL END-face M2.5 holes: each STS3215 +/-X end\n"
        "  face carries a 10 x 10 mm square of 4 M2.5 case holes (measured\n"
        "  Waveshare ST3215), and every cradle drives 4 x M2.5 x 8 SHCS\n"
        "  through its -X wall into that square (`91290A104`, 4 per cradle\n"
        "  x 3 cradles x 6 legs = 72; head recessed in a wall counterbore,\n"
        "  threads into the servo's own metal case).  This positively bolts\n"
        "  the servo instead of only gripping it; the hip/knee clamp cap\n"
        "  and the yaw retainer strap are retained as secondary capture.\n"
        "- Link-to-disc-horn bolts (72 x M3x6 SHCS / `91290A111`) thread\n"
        "  into the 20 mm aluminum 25T disc horn's M3 TAPPED holes on a\n"
        "  14 mm bolt circle (cross pattern at 0/90/180/270 deg); the\n"
        "  aluminum is the thread-engagement medium -- no self-tap, no\n"
        "  heat-set (June 2026 disc-horn switch, retiring the now-retired\n"
        "  plastic 4-arm X-horn's M2x8 self-tap scheme).  See\n"
        "  `fasteners/README.md` for the full rationale.\n"
        "- Captive nyloc nuts are used at the foot-pad hinge pins (6 total,\n"
        "  one per leg); the through-hole bolt is captured by the nyloc on\n"
        "  the opposite side of the foot.  The previous 24 x M3 x 14\n"
        "  coxa-bracket-to-chassis nyloc'd through-bolts were retired in\n"
        "  the May 2026 chassis_bottom-integrated yaw cradle redesign --\n"
        "  the printed bracket flange they clamped is gone, replaced by\n"
        "  per-leg cradle bosses inside chassis_bottom.\n"
        "- The M2.5 spline center screw ships with each STS3215 servo --\n"
        "  it's listed here so the screwdriver-access verifier check knows the\n"
        "  fastener exists, but you do NOT order it separately.\n"
        "- See `fasteners/README.md` for the McMaster STEP swap-in flow if you\n"
        "  want to replace the parametric fallback geometry with real CAD.\n"
        "\n"
        f"{END}\n"
    )


def inject_into(path: str) -> bool:
    """Rewrite the BEGIN/END section in ``path`` in place.  Returns
    True on success, False if the markers are missing (in which case
    the caller should append the section manually)."""
    with open(path, "r") as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        return False
    pre, _, rest = text.partition(BEGIN)
    _, _, post = rest.partition(END)
    new = pre + render_section().rstrip() + post
    if new != text:
        with open(path, "w") as f:
            f.write(new)
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Print the auto-derived fastener BOM markdown table, or "
            "inject it into a markdown file between the "
            "<!-- BEGIN FASTENERS --> / <!-- END FASTENERS --> markers."
        ),
    )
    ap.add_argument(
        "--inject",
        metavar="PATH",
        action="append",
        default=[],
        help=(
            "Rewrite the BOM section in PATH in place.  Repeat to "
            "update multiple files at once."
        ),
    )
    args = ap.parse_args(argv)
    if args.inject:
        ok = True
        for path in args.inject:
            if not inject_into(path):
                print(f"render_fastener_bom: no <!-- BEGIN FASTENERS --> "
                      f"marker in {path}; section not updated",
                      file=sys.stderr)
                ok = False
            else:
                print(f"render_fastener_bom: updated {path}")
        return 0 if ok else 1
    print(render_section())
    return 0


if __name__ == "__main__":
    sys.exit(main())
